version: '2.1'
services:
  logging-fake-kibana:
    extends:
      file: services/logging/fake-kibana/docker-compose.yml
      service: service
    ports:
      - 5601:5601
  logging-fake-logstash-elb:
    extends:
      file: services/logging/fake-logstash-elb/docker-compose.yml
      service: service
  logging-logstash:
    extends:
      file: ${LOGGING_SANDBOX_DIRECTORY_PATH:-.}/services/logging/logstash/docker-compose-${LOGGING_DOCKER_COMPOSE_SERVICE_MODE:-build}.yml
      service: service
    ports:
      - 5044:5044