---
- src: ${ansible_role_repository_base_url}/aptitude_package_recipient/${aptitude_package_recipient_version}/aptitude_package_recipient
- src: ${ansible_role_repository_base_url}/automation_server/${automation_server_version}/automation_server
- src: ${ansible_role_repository_base_url}/aws_ssh_server/${aws_ssh_server_version}/aws_ssh_server
- src: ${ansible_role_repository_base_url}/long_running_host/${long_running_host_version}/long_running_host
- src: ${ansible_role_repository_base_url}/clock_synchronization_host/${clock_synchronization_host_version}/clock_synchronization_host
