---
- src: ${ansible_role_repository_base_url}/aptitude_package_recipient/${aptitude_package_recipient_version}/aptitude_package_recipient
- src: ${ansible_role_repository_base_url}/automater/${automater_version}/automater
- src: ${ansible_role_repository_base_url}/automation_agent/${automation_agent_version}/automation_agent
- src: ${ansible_role_repository_base_url}/aws_api_client/${aws_api_client_version}/aws_api_client
- src: ${ansible_role_repository_base_url}/aws_ssh_server/${aws_ssh_server_version}/aws_ssh_server
- src: ${ansible_role_repository_base_url}/container_factory/${container_factory_version}/container_factory
- src: ${ansible_role_repository_base_url}/frontend_project_builder/${frontend_project_builder_version}/frontend_project_builder
- src: ${ansible_role_repository_base_url}/long_running_host/${long_running_host_version}/long_running_host
- src: ${ansible_role_repository_base_url}/java_project_builder/${java_project_builder_version}/java_project_builder
- src: ${ansible_role_repository_base_url}/ssrn_system_simulator/${ssrn_system_simulator_version}/ssrn_system_simulator
- src: ${ansible_role_repository_base_url}/browser_test_runner/${browser_test_runner_version}/browser_test_runner
- src: ${ansible_role_repository_base_url}/clock_synchronization_host/${clock_synchronization_host_version}/clock_synchronization_host
