version: '2.1'
services:
  fake-cdn:
    extends:
      file: ../../test/support/fake-cdn/docker-compose.yml
      service: service
    ports:
      - "80:80"
      - "81:81"
  fake-load-balancer:
    extends:
      file: ../../test/support/fake-load-balancer/docker-compose.yml
      service: service
  search-api:
    extends:
      file: api/docker-compose-${SEARCH_DOCKER_COMPOSE_SERVICE_MODE:-build}.yml
      service: service
    environment:
      - ELASTICSEARCH_ENDPOINT=http://search-papers-index.oxford-north-1.es.amazonaws.local:9200
      - AWS_ACCESS_KEY_ID=dummy
      - AWS_SECRET_ACCESS_KEY=dummy
      - SHIP_LOGS=false
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.3.0
    cap_add:
      - IPC_LOCK
    ports:
      - 9200:9200
    environment:
      - xpack.security.enabled=false
      - cluster.name=search-cluster
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    networks:
      default:
        aliases:
          - search-papers-index.oxford-north-1.es.amazonaws.local
  search-papers-consumer:
    extends:
      file: papers-consumer/docker-compose-${SEARCH_DOCKER_COMPOSE_SERVICE_MODE:-build}.yml
      service: service
    environment:
      - ELASTICSEARCH_ENDPOINT=http://search-papers-index.oxford-north-1.es.amazonaws.local:9200
      - AWS_ACCESS_KEY_ID=dummy
      - AWS_SECRET_ACCESS_KEY=dummy
      - SHIP_LOGS=false
      - LOG_INDIVIDUAL_PAPERS=true
      - KINESIS_STREAM_NAME=papers
      - KCL_APPLICATION_NAME=paperConsumer
  fake-papers-service:
    extends:
      file: papers-consumer/fake-papers-service/docker-compose.yml
      service: service
  fake-authors-service:
      extends:
        file: author-updates-subscriber/fake-authors-service/docker-compose.yml
        service: service
  kinesis:
    extends:
      file: ../../test/support/fake-kinesis/docker-compose.yml
      service: service
    ports:
      - "4567:4567"
      - "8000:8000"
  search-author-updates-subscriber:
      extends:
        file: author-updates-subscriber/docker-compose-${SEARCH_DOCKER_COMPOSE_SERVICE_MODE:-build}.yml
        service: service
      environment:
        - ELASTICSEARCH_ENDPOINT=http://search-papers-index.oxford-north-1.es.amazonaws.local:9200
        - AWS_ACCESS_KEY_ID=dummy
        - AWS_SECRET_ACCESS_KEY=dummy
        - SHIP_LOGS=false
        - LOG_INDIVIDUAL_AUTHORS=true
        - KINESIS_STREAM_NAME=author-updates
        - KCL_APPLICATION_NAME=authorUpdatesSubscriber